apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgsql-deployment
  labels:
    app: pgsql
    tier: database
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pgsql
      tier: database
  template:
    metadata:
      labels:
        app: pgsql
        tier: database
    spec:
      containers:
        - name: pgsql-pod
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: pgsql-config
                  key: POSTGRES_USER

            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: pgsql-config
                  key: POSTGRES_DB

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgsql-secret
                  key: PASSWORD
